[0m17:36:45.606004 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020F42FDA2C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020F4426CDC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020F4426CBB0>]}


============================== 17:36:45.611747 | 5a43f721-96e4-4803-9b7c-1c2db6e2daf3 ==============================
[0m17:36:45.611747 [info ] [MainThread]: Running with dbt=1.10.6
[0m17:36:45.611747 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\samee\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt init f1_analytics', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m17:36:45.639653 [info ] [MainThread]: Creating dbt configuration folder at C:\Users\samee\.dbt
[0m17:36:45.642680 [debug] [MainThread]: Starter project path: C:\Users\samee\Desktop\F1\.venv\lib\site-packages\dbt\include\starter_project
[0m17:36:45.669677 [info ] [MainThread]: 
Your new dbt project "f1_analytics" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m17:36:45.669677 [info ] [MainThread]: Setting up your profile.
[0m17:03:09.610745 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000207BE11A200>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000207C0374E80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000207C0374C10>]}


============================== 17:03:09.615838 | 764cfa76-b4fe-423b-8b74-7025e19bee11 ==============================
[0m17:03:09.615838 [info ] [MainThread]: Running with dbt=1.10.6
[0m17:03:09.616838 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\samee\\.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run --select stg_drivers.sql', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m17:03:09.616838 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\samee\Desktop\F1\include\malay\scripts\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:03:09.618171 [debug] [MainThread]: Command `dbt run` failed at 17:03:09.618171 after 0.08 seconds
[0m17:03:09.619391 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000207BE11A200>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000207C0374F70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000207C0374F40>]}
[0m17:03:09.620194 [debug] [MainThread]: Flushing usage events
[0m17:03:10.749923 [debug] [MainThread]: An error was encountered while trying to flush usage events
